import argparse
import sys
from pathlib import Path

from .config import (
    DEFAULT_MIN_REPO_PRS,
    DEFAULT_PR_PAGE_SIZE,
    DEFAULT_PR_SLEEP_SECONDS,
    DEFAULT_PRS_CSV,
    DEFAULT_REPO_PAGE_SIZE,
    DEFAULT_REPO_SLEEP_SECONDS,
    DEFAULT_REPOSITORY_SEARCH_QUERY,
    DEFAULT_SELECTED_REPOS_CSV,
    DEFAULT_TARGET_REPOSITORIES,
    PR_DATASET_FIELDS,
    REPOSITORY_SELECTION_FIELDS,
)
from .github_data import fetch_pull_requests_dataset, fetch_selected_repositories
from .io_utils import load_csv, save_csv


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Lab 3 - Sprint 1 only: repository selection and pull request dataset collection."
        )
    )
    subparsers = parser.add_subparsers(dest="command")

    collect_repos_parser = subparsers.add_parser(
        "collect-repos",
        help="Select top repositories that satisfy the minimum amount of merged+closed PRs.",
    )
    collect_repos_parser.add_argument(
        "--target-repositories",
        type=int,
        default=DEFAULT_TARGET_REPOSITORIES,
        help="How many repositories should be selected (default: 200).",
    )
    collect_repos_parser.add_argument(
        "--min-repo-prs",
        type=int,
        default=DEFAULT_MIN_REPO_PRS,
        help="Minimum merged+closed PRs required per repository.",
    )
    collect_repos_parser.add_argument(
        "--search-query",
        default=DEFAULT_REPOSITORY_SEARCH_QUERY,
        help="GitHub search query used to rank repositories by popularity.",
    )
    collect_repos_parser.add_argument(
        "--page-size",
        type=int,
        default=DEFAULT_REPO_PAGE_SIZE,
        help="GraphQL page size for repository search.",
    )
    collect_repos_parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=DEFAULT_REPO_SLEEP_SECONDS,
        help="Delay between repository page requests.",
    )
    collect_repos_parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_SELECTED_REPOS_CSV,
        help="Output CSV path for selected repositories.",
    )

    collect_prs_parser = subparsers.add_parser(
        "collect-prs",
        help="Collect PR-level metrics for selected repositories.",
    )
    collect_prs_parser.add_argument(
        "--repos-csv",
        type=Path,
        default=DEFAULT_SELECTED_REPOS_CSV,
        help="CSV generated by collect-repos.",
    )
    collect_prs_parser.add_argument(
        "--pr-page-size",
        type=int,
        default=DEFAULT_PR_PAGE_SIZE,
        help="GraphQL page size for pull request pagination.",
    )
    collect_prs_parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=DEFAULT_PR_SLEEP_SECONDS,
        help="Delay between pull request page requests.",
    )
    collect_prs_parser.add_argument(
        "--max-prs-per-repo",
        type=int,
        default=None,
        help="Optional cap for quick smoke runs.",
    )
    collect_prs_parser.add_argument(
        "--repo-limit",
        type=int,
        default=None,
        help="Optional cap of repositories loaded from repos-csv.",
    )
    collect_prs_parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_PRS_CSV,
        help="Output CSV path for PR dataset.",
    )

    sprint1_parser = subparsers.add_parser(
        "sprint1",
        help="Run Sprint 1 end-to-end: collect repositories and then collect PR dataset.",
    )
    sprint1_parser.add_argument(
        "--target-repositories",
        type=int,
        default=DEFAULT_TARGET_REPOSITORIES,
    )
    sprint1_parser.add_argument(
        "--min-repo-prs",
        type=int,
        default=DEFAULT_MIN_REPO_PRS,
    )
    sprint1_parser.add_argument(
        "--search-query",
        default=DEFAULT_REPOSITORY_SEARCH_QUERY,
    )
    sprint1_parser.add_argument(
        "--repo-page-size",
        type=int,
        default=DEFAULT_REPO_PAGE_SIZE,
    )
    sprint1_parser.add_argument(
        "--pr-page-size",
        type=int,
        default=DEFAULT_PR_PAGE_SIZE,
    )
    sprint1_parser.add_argument(
        "--repo-sleep-seconds",
        type=float,
        default=DEFAULT_REPO_SLEEP_SECONDS,
    )
    sprint1_parser.add_argument(
        "--pr-sleep-seconds",
        type=float,
        default=DEFAULT_PR_SLEEP_SECONDS,
    )
    sprint1_parser.add_argument(
        "--max-prs-per-repo",
        type=int,
        default=None,
    )
    sprint1_parser.add_argument(
        "--selected-repos-output",
        type=Path,
        default=DEFAULT_SELECTED_REPOS_CSV,
    )
    sprint1_parser.add_argument(
        "--prs-output",
        type=Path,
        default=DEFAULT_PRS_CSV,
    )

    return parser.parse_args()


def _limit_repositories(rows, limit):
    if limit is None:
        return rows
    return rows[: max(limit, 0)]


def run() -> None:
    args = parse_args()

    if not args.command:
        print("Use one command: collect-repos, collect-prs, sprint1")
        sys.exit(1)

    try:
        if args.command == "collect-repos":
            repositories = fetch_selected_repositories(
                target_repositories=args.target_repositories,
                min_repo_prs=args.min_repo_prs,
                page_size=args.page_size,
                search_query=args.search_query,
                sleep_seconds=args.sleep_seconds,
            )
            save_csv(repositories, args.output, REPOSITORY_SELECTION_FIELDS)
            return

        if args.command == "collect-prs":
            repository_rows = load_csv(args.repos_csv)
            repository_rows = _limit_repositories(repository_rows, args.repo_limit)
            dataset = fetch_pull_requests_dataset(
                selected_repositories=repository_rows,
                pr_page_size=args.pr_page_size,
                sleep_seconds=args.sleep_seconds,
                max_prs_per_repo=args.max_prs_per_repo,
            )
            save_csv(dataset, args.output, PR_DATASET_FIELDS)
            return

        if args.command == "sprint1":
            repositories = fetch_selected_repositories(
                target_repositories=args.target_repositories,
                min_repo_prs=args.min_repo_prs,
                page_size=args.repo_page_size,
                search_query=args.search_query,
                sleep_seconds=args.repo_sleep_seconds,
            )
            save_csv(repositories, args.selected_repos_output, REPOSITORY_SELECTION_FIELDS)

            dataset = fetch_pull_requests_dataset(
                selected_repositories=repositories,
                pr_page_size=args.pr_page_size,
                sleep_seconds=args.pr_sleep_seconds,
                max_prs_per_repo=args.max_prs_per_repo,
            )
            save_csv(dataset, args.prs_output, PR_DATASET_FIELDS)
            return

        raise RuntimeError(f"Unsupported command: {args.command}")

    except Exception as exc:
        print(f"ERROR: {exc}")
        sys.exit(1)
